/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    java

    idea

    id("com.palantir.graal") version "0.3.0-20-g2be40b9"
    /*
    // Apply the application plugin to add support for building an application
    application
    */
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}


dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    implementation("com.google.guava:guava:27.0.1-jre")
    implementation("com.netflix.devinsight.rewrite:rewrite-core:1.2.0")
    implementation("com.google.code.gson:gson:2.8.5")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

/*
application {
    // Define the main class for the application
    mainClassName = "windinglines.jusage.App"
}
*/

graal {
    mainClass("windinglines.jusage.App")
    outputName("jusage")
    graalVersion("1.0.0-rc15")
}
