/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package windinglines.jusage;

import org.junit.Test;

import static org.junit.Assert.*;


public class SimpleAppTest {
  @Test
  public void testAppHasAGreeting() {
    SimpleApp classUnderTest = new SimpleApp();
    assertNotNull("app should have a greeting", classUnderTest);
  }
}
