/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package windinglines.jusage;

import java.io.IOException;
import windinglines.jusage.simple.Indexer;


/**
 * Entry point, expects the following command line arguments:
 *
 * - base_folder: contains subprojects to be analysed
 * - package: package of classes to be tracked
 */
public class SimpleApp {
  public static void main(String[] args) {
    if (args.length != 2) {
      System.err.println("jusage: package base_folder");
      return;
    }
    String packageName = args[0];
    String baseFolder = args[1];
    Indexer parser = new Indexer(baseFolder, packageName);
    try {
      parser.build();
      parser.write();
      System.out.println("Output " + parser.getDbPath());
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
